// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_file`, `display_name`, `format_gain`, `format_peak`, `peak_from_result`, `values_from_result`, `write_album_gain`, `write_track_gain`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LoudnessResult`

Stream<ReplayGainProgress> writeReplayGain({
  required List<String> paths,
  required ReplayGainScanMode mode,
}) => RustLib.instance.api.crateApiReplayGainWriteReplayGain(
  paths: paths,
  mode: mode,
);

class ReplayGainProgress {
  final BigInt completed;
  final BigInt total;
  final String message;
  final BigInt failed;

  const ReplayGainProgress({
    required this.completed,
    required this.total,
    required this.message,
    required this.failed,
  });

  @override
  int get hashCode =>
      completed.hashCode ^ total.hashCode ^ message.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplayGainProgress &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          total == other.total &&
          message == other.message &&
          failed == other.failed;
}

enum ReplayGainScanMode { album, track }
